eclipse-uprotocol/up-spec

basics/cloudevents.adoc, up-l2/dispatchers/README.adoc
Define optional uAttribute (`traceparent`) that is compatible with the [CloudEvents Distributed Tracing extension](https://github.com/cloudevents/spec/blob/main/cloudevents/extensions/distributed-tracing.md) and industry norms to support proper end-to-end observability. This is especially valuable for [more complex situations](https://github.com/cloudevents/spec/blob/main/cloudevents/extensions/distributed-tracing.md#using-the-distributed-tracing-extension).  One example could be where a UE may raise an event as a result of another event.
Example: 
1. Vehicle's session service publishes an `trip started` event (id=`abc123`)
2. A driver app receives the event, looks up driver's identity, and D.O.T. log to see first drive of the day.  Driver app publishes `shift_started` event (id=`xyz456`, …
=> Distributed tracing

up-l2/rpcclient.adoc
The following chance replaces UAttributes with CallOptions that are defined in uattributes.proto
#69
=> RpcClient Update to match implementations

up-l1/README.adoc
From #68, namely from [this clarification](https://github.com/eclipse-uprotocol/up-spec/issues/68#issuecomment-2007523728)
Updated to reflect that the minimum viable UUri that we should accept in UTransport::send() is that which satisfies the Micro Form.
=> Clarification of minimum viable UUri as being one that satisfies Micro Form

up-l1/README.adoc
Updating UTransport::registerListener() and UTransport::unregisterListener() to clarify that they take _at a minimum_ a UUri which satisfies isMicroForm() but SHOULD be passed Resolved UUris.
For issue #98
=> Clarification of minimum viable UUri as being one that satisfies Micro Form for `UTransport::registerListener()` and `UTransport::unregisterListener`

up-core-api/uprotocol/uri.proto
This PR implements issue #102 
It modifies uri.proto:
1. UEntity name is now optional
2. UResource name is now optional
=> Making Uri proto, microuri support mandatory and longuri support optional

up-core-api/uprotocol/uri.proto
The following adds to #121 to simplify the datamodel for UUri object.
=> Simplification of UUri Data model

up-core-api/uprotocol/upayload.proto
The following change removes the notion of passing data by reference in UPayload till we finalize the shared memory APIs.
#128
=> Cleanup of UPayload

up-core-api/uprotocol/uattributes.proto
CallOptions is never sent as a uProtocol message. Instead of being a layer-0 message, it was used as a layer-2 client API.
It is being removed in favor of allowing language-specific API libraries to define the most appropriate function signatures for the language.
Addresses issue #132
=> Remove the CallOptions message

basics/uattributes.adoc, basics/uri.adoc
The invariants for UUri's used in a certain context have been moved
from the UUri to the UAttributes specification where they are now
defined in the proper (message type) context.
=> Move UUri invariants to UAttributes specification

up-core-api/uprotocol/v1/uri.proto
The UUri specification contains all relevant definitions and
requirements for a URI's components. The proto3 file simply defines
the encoding to use when sending UUris over the wire.
All comments containing field definitions/requirements have been
removed in order to prevent diverging semantics.
=> Align uri.proto with spec

up-l1/zenoh.adoc
The PR is to deal with
* The mapping of UUri and Zenoh Key: https://github.com/eclipse-uprotocol/up-spec/issues/100
* Using short UUri for Zenoh Key: https://github.com/eclipse-uprotocol/up-spec/issues/83
Still need to wait for #92 before merging (I need to add some changes)
=> Conform Zenoh spec to 1.5.8

basics/error_model.adoc
=> Add RPC response message usage definition

up-core-api/uprotocol/core/udiscovery/v3/udiscovery.proto, up-core-api/uprotocol/core/usubscription/v3/usubscription.proto, up-core-api/uprotocol/core/utwin/v2/utwin.proto
Changed operation definitions of uProtocol core services to always
use dedicated request and response messages as recommended by
Protobuf Best Practices.
Removed UStatus from response messages, following recommendations
from uProtocol Error Model specification.
This is a follow up for #112
=> Use dedicated messages in service operations

basics/uuid.adoc, up-core-api/uprotocol/v1/uuid.proto
After further study of the UUID specifications, there was a concern that fixing rand_b per instantiation of the uE could result in two events being generated with the same UUID if the time jumps back (due to corrections).
#170
=> Replace UUIDv8 for UUIDv7

up-l1/README.adoc
The Transport Layer API (L1) has been extended with a LocalUriProvider
interface that can be used to create UUris representing a uEntity's
local resources.
addresses #177
=> Add support for creating local resource UUris

up-l1/mqtt_5.adoc
Certain messaging brokers handle zero-length segments differently for topics, as such we will simply remove the zero length segments if the sink uri is 'None'
=> removed zero-length segments from mqtt 5 spec

up-core-api/uprotocol/v1/uattributes.proto, up-core-api/uprotocol/v1/ucode.proto, up-core-api/uprotocol/v1/ustatus.proto
Mechatronics world would like to use UCode that that we have consistent definitions of errors codes across all uServices however they cannot and will not use UStatus that also includes string messages and repeated any (that is more used for high-compute services. Although they can still achieve their goal by only using UCode from uservice.proto, splitting them means we can add the SOME/Ip serialization metadata (CustomOptions) to the ucode.proto and we do not have do do that for ustatus.proto.
#173
=> Separate UCode from UStatus

up-core-api/uprotocol/v1/uattributes.proto
Once I committed #173 I caused an issue with a warning that appears that ustatus proto is included in uattributes.proto even though it is not used so this issue will be used to remove the warning.
#185
=> Fix warning for unused ustatus.proto

basics/uri.adoc
Some of the OpenFastTrace specification item names did not contain any
any reference to the UUri scope. They have been prefixed with "uri-".
=> Reflect UUri scope in OFT spec item names

up-l1/README.adoc
Calling the UTransport register and unregister API multiple times with the same parameters return the same value as if you called it the first time in lieu of returning  `UCode.ALREADY_EXISTS`.
#193
=> Add idempotent requirement to UTransport APIs.

languages.adoc
THis is for #197]
Some of the items have been dropped because they should be included in
the specification documents of uProtocol's basic types instead.
A title has been added to all spec items which indicates the item's
purpose.
Some items have been split up into multiple items and/or rephrased to
improve readability.
=> Improve Language Library's OFT specification items

.gitignore
Changed all absolute paths in gitignore so that the paths are
also being ignored when including up-spec as a git submodule from
other repos (as we do from up-rust).
=> Use relative paths in gitignore

up-l1/zenoh.adoc
I wasn't aware of the stable release of Zenoh 0.11.0 before. Using the stable one instead of the RC version would be better.
=> Use stable Zenoh version 0.11.0 instead of RC.

basics/uattributes.adoc, up-l1/mqtt_5.adoc
The following changes adds D2D usecase for the MQTT5 transport, fixes the uE-2-uE use case, and adds OFT tags to uatributes and MQTT5 specs.
#192, #169
=> Updates to uattributes and MQTT5 specifications

basics/error_model.adoc
When the service fails to successfully process the request message, it must populate comstatus vs should.
#214
=> Clarification for populating comstatus for RPC request failure

up-l1/zenoh.adoc
Since most of the APIs are stable now, it's time to move forward to the Zenoh 1.0 version.
Loop @neelam-kushwah @PLeVasseur @sashacmc @stevenhartley
=> Bump Zenoh to 1.0.0-alpha.6

up-l1/README.adoc
The transport needs to verify that the caller (client) source address is the same as what is in the passed `UMessage` of the send() API to avoid any uE from spoofing another uE.  The only exception for this rule is if the uE is the streamer who is simply forwarding events from one transport to the next and in that case the streamers identity needs to be verified upon creation of the transport.
The PR also adds in missing OFT metadata.
#218
=> Adding OFT metadata and uTransport address spoofing check.

basics/uri.adoc
The following change adds some verbiage that states that it is valid to not set the instance_id that indicates that we do not care. This is often used when referring to services that do not have more than one instance.
This change is to help clarify the requirements after looking at the C++ UUri validators.
also minor fixes to the specifications w.r.t pattern matching for resource_id
#217
=> URI ue instance id wildcard 0xFFFF in lieu of 0x0000

up-core-api/uprotocol/core/usubscription/v3/usubscription.proto
The SubscriberInfo was a wrapper for the subscribers URI however it passes details that was never used (and complicates the implementations) and is passed in some scenarios that is redundant (we know who is calling the APIs). The SubscriberInfo is also passed to registerForNotifications however subscribers don't call this API so it is confusing for developers.
#220
=> Remove unused SubscriberInfo from some USubscription messages

basics/uri.adoc
The revision number of the specification item for the Pattern Matching
requirements has been increased to reflect the semantic change to
the service instance ID wildcard value.
This addresses #217
=> Change OFT spec item revision

up-l1/zenoh.adoc
Zenoh is a technology that supports uProtocol L1 and L2 functionality however we have sandwiched it into the L1 uTransport interface and then expected it to be optimized and do some L2 stuff below L1 (see the confusion). The following change will state that implementations will ONLY use the pub/sub of zenoh such that it can simply send() and receive UMessages and we leave the L2 functionality (ex. RPC corelation) up to the uProtocol language libraries.
=> Use Zenoh for L1 Transport Only

up-l1/zenoh.adoc
There are some updates in Zenoh spec:
* Fix Zenoh version to 1.0.0
* Fix some out-dated terms, like `up-client` => `up-transport`
* Update the user attachment mechanism
=> Update the Zenoh spec to match Zenoh 1.0

basics/upayloadformat.adoc, up-core-api/uprotocol/v1/uattributes.proto
Previously (version 1.3.6 and earlier of the specification) we did not have an enum for the payload format (it was a string) and sending the string was costly to the cloud even though we always knew it was WRAPPED_IN_ANY. To avoid sending the payload format we omitted the attribute and then  "assumed" that if it was not present it would be WRAPPED_IN_ANY.  Now that we have an enum defined, it is better to remove the ambiguity of this attribute and make it explicit, this means that if someone sets it to UNSPECIFIED it really means unspecified (we don't know or are not setting it to anything). Additionally, for SOME/IP there is no way to pass this attribute (UPayloadFormat) so we have to set UPayloadFormat as UNSPECIFIED and then leave it up to the client to know the format from the source. …
=> Remove ambiguity for UNSPECIFIED UPayloadFormat

up-core-api/uprotocol/core/ustreamer/v1/ustreamer.proto, up-core-api/uprotocol/core/utwin/v2/utwin.proto, up-l3/README.adoc
In order to ensure that there is no overlap of assignment of names and/or numbers of uEs, this commit will add in basic rules for reserving names/numbers for specific purposes.
#67
=> Add Initial name & number Registry Requirements

up-core-api/uprotocol/core/utwin/v2/utwin.proto
The set API is not part of the public APIs that clients will use so it needs to be removed.
#221
=> Remove Set API from uTwin

up-l1/mqtt_5.adoc
The uEntity type and instance IDs contained in the ue_id field of
a UMessage are now being put into separate segments of topic names and
filters to support accepting any uEntity instance ID in topic filters.
Additionally, the mappign of UAttributes::ttl has been changed to use
the standard Message Expiry Interval property of the MQTT 5 PUBLISH
packet instead of using a User Property. This allows for taking
advantage of an MQTT broker's message expiration functionality.
=> Put uEntity instance ID into dedicated topic segment

.gitignore, up-l3/udiscovery/v3/service.adoc
A malformed OFT spec item identifier causees the OFT check to fail
=> Fix OFT spec item identifier

up-l1/mqtt_5.adoc
Adapted the mapping of UAttribute fields to make use of standard
properties defined in MQTT 5.
Also removed the distinct spec item identifiers defined for each field.
The mapping of the fields will most likely happen in very coherent
code blocks (functions) so it should be sufficient to trace the
requirements at that level.
I wonder if we should also adapt the mapping of the message ID to use hex encoding instead of the hyphenated string representation. WDYT? @PLeVasseur @ValMobBIllich
=> Make use of existing MQTT 5 header properties

up-l1/zenoh.adoc
Restructured the Zenoh transport specification along the lines of the MQTT 5 transport spec to better support adding OFT specitem definitions.
This is for #169
=> Add OFT specitem definitions

README.adoc, basics/error_model.adoc, languages.adoc, up-l1/README.adoc, up-l2/README.adoc, up-l2/api.adoc
Some of the requirements in the Language Library, L1 and L2 specs need
to be covered by language libraries while others need to be implemented
by transport libraries.
In order to allow different components to filter out those specitems
that are relevant for them, OFT supports tags to be defined by
specification items.
The relevant tags can then be specified during the OFT trace run.
Also replaced links with xrefs, improved wording, added requirements
regarding listener invocation.
=> Add tags to OFT specification items

up-l1/mqtt_5.adoc
The mapping of a UMessage's TTL value to an MQTT 5 message's
Message Expiry Interval property using the ceil function has resulted
in the receiving side not being able to retain the original TTL value
if the TTL had sub-second granularity.
This has been fixed by requiring implementors to also add a User
Property containing the original TTL value in such cases.
Fixes #268
=> [#268] Retain sub-second granularity TTL value

basics/uattributes.adoc
The specification item that defines requirements for an RPC response
message's priority attribute had been using a misleading identifier.
This has been fixed.
=> Fix specitem identifier for response priority value

up-l3/udiscovery/v3/service.adoc
This typo makes oft bark on requirements analysis runs, so fix it.
=> Fix typo in requirement ID that breaks oft runs

up-core-api/uprotocol/core/usubscription/v3/usubscription.proto, up-l3/usubscription/v3/README.adoc
uSubscription: as per discussion in #282, this PR removes protobuf attributes and requirements associated with the pagination of lists returned by getSubscribers/getSubscriptions.
I've not taken the detour of deprecating these attributes first - as we're not in production for now, I'm thinking we can directly remove&reserve these properties.
=> Remove subscriber/subscription list pagination

up-l1/README.adoc, up-l1/mqtt_5.adoc, up-l1/zenoh.adoc
The Zenoh and the MQTT 5 transport spec have been amended to cover
some generic requirements from the Transport Layer specification
by default. This relieves implementations from creating corresponding
spec items which do contain anything specific to the implementation.
=> Cover UTransport requirements by default

basics/uuid_string_serialization.feature
The Gherkin scenarios for verifying UUID serialization to its
hex-and-dash string representation have been adapted to refer to the
specific OFT specitem from the UUID specification document.
=> Fix covered OFT specitem ID

up-l3/usubscription/v3/README.adoc
In usubscription spec, there was a copy-paste induced duplication of a requirement id - this PR fixes that.
=> Fix copy-paste duplication of req id

up-l3/usubscription/v3/README.adoc
Requirements around protobuf usage were missing test-needed attribute; adding that.
=> Add test-required attribute to some requirements

up-l3/usubscription/v3/README.adoc
Fix minor oversight: `dsn~usubscription-reset-protobuf~1` should also demand a test.
=> Add missing utest attribute for reset-protobuf requirement

basics/uuri_pattern_matching.feature, basics/uuri_uri_serialization.feature
Add unambiguous example values for server-based authorities which should
fail to be deserialized as UURIs.
Removed invalid pattern URI from scenario. Also added more example
values to increase coverage.
Fixes #300 and #302
=> Fix/Improve UURI Gherkin features
